name = "theo-home"
compatibility_date = "2026-08-05"
workers_dev = true

[assets]
directory = "./public"
html_handling = "drop-trailing-slash"
not_found_handling = "single-page-application"

[[routes]]
pattern = "home.theoazriel.com"
custom_domain = true
